name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: npm i
      - run: mkdir -p dist && npm run package
      - uses: actions/upload-artifact@v7
        with:
          name: xiaomimimo-for-copilot.vsix
          path: dist/*.vsix